# AUTOGENERATED - DO NOT EDIT.
# If you need to customize defaults, create/modify local_overrides.mk.
# This Makefile discovers tests/**/test_runner.c and builds one selected test at a time.

# ========== Shell & Debug ==========
SHELL := /bin/bash
DEBUG ?= 0
ifeq ($(DEBUG),1)
  .SHELLFLAGS := -ex -o pipefail -c
else
  .SHELLFLAGS := -e -o pipefail -c
endif
Q ?= @

# ----- Optional local overrides -----
-include local_overrides.mk

# ========== Toolchain & NeuralSPOT integration ==========
ifeq ("$(wildcard neuralspot)","")
$(error NeuralSPOT not found. Please init/sync submodules so ./neuralspot exists.)
endif

# Put toolchain on PATH *before* including anything that might probe it
ARM_GCC_PATH := $(abspath downloads/arm_gcc_download/bin)
ifneq ("$(wildcard $(ARM_GCC_PATH)/arm-none-eabi-gcc)","")
  $(info Using downloaded ARM GCC toolchain from $(ARM_GCC_PATH))
  export PATH := $(ARM_GCC_PATH):$(PATH)
else
  $(error ARM GCC toolchain not found at $(ARM_GCC_PATH). Run setup_dependencies.py first.)
endif

include neuralspot/make/helpers.mk
include neuralspot/make/neuralspot_config.mk
include neuralspot/make/neuralspot_toolchain.mk
include neuralspot/make/jlink.mk
# include makefile_wrapper_call.mk

# ========== Toolchain family ==========
ifeq ($(TOOLCHAIN),arm)
  COMPDIR := armclang
else ifeq ($(TOOLCHAIN),arm-none-eabi)
  COMPDIR := gcc
else
  $(warning TOOLCHAIN not set; defaulting to arm-none-eabi)
  TOOLCHAIN := arm-none-eabi
  COMPDIR := gcc
endif

# Absolute tools used in recipes
RUN_CC      := $(ARM_GCC_PATH)/arm-none-eabi-gcc
RUN_CXX     := $(ARM_GCC_PATH)/arm-none-eabi-g++
RUN_AR      := $(ARM_GCC_PATH)/arm-none-eabi-ar
RUN_LD      := $(ARM_GCC_PATH)/arm-none-eabi-ld
RUN_OBJCOPY := $(ARM_GCC_PATH)/arm-none-eabi-objcopy
RUN_OBJDUMP := $(ARM_GCC_PATH)/arm-none-eabi-objdump
RUN_SIZE    := $(ARM_GCC_PATH)/arm-none-eabi-size
RUN_STRIP   := $(ARM_GCC_PATH)/arm-none-eabi-strip

# Also publish classic vars so included mk files pick them up
override CC      := $(RUN_CC)
override CXX     := $(RUN_CXX)
override AR      := $(RUN_AR)
override LD      := $(RUN_LD)
override OBJCOPY := $(RUN_OBJCOPY)
override OBJDUMP := $(RUN_OBJDUMP)
override SIZE    := $(RUN_SIZE)
override STRIP   := $(RUN_STRIP)
override CP      := $(RUN_OBJCOPY)
override OD      := $(RUN_OBJDUMP)
export CC CXX AR LD OBJCOPY OBJDUMP SIZE STRIP CP OD

AS_VERSION := R5.3.0

# ========== Module set ==========
modules      := neuralspot/neuralspot/ns-core
modules      += neuralspot/neuralspot/ns-harness
modules      += neuralspot/neuralspot/ns-peripherals
modules      += neuralspot/neuralspot/ns-ipc
modules      += neuralspot/neuralspot/ns-audio
modules      += neuralspot/neuralspot/ns-utils
modules      += neuralspot/neuralspot/ns-uart
modules      += neuralspot/neuralspot/ns-features
modules      += neuralspot/neuralspot/ns-i2c
modules      += neuralspot/neuralspot/ns-spi
# modules      += neuralspot/neuralspot/ns-rpc  # Disabled - requires USB support
# modules      += neuralspot/neuralspot/ns-usb  # Disabled - requires TinyUSB
# Add-ons used by CMSIS-NN testing (present in example repo)
modules      += ns-cmsis-nn
# modules      += ns-cmsis-dsp
# modules      += modules/GeneratedTests
# extern
# modules      += neuralspot/extern/erpc/R1.9.1  # Disabled - requires USB support

# ========== TinyUSB detection / conditional USB module ==========
# Turn on if you actually need USB. If TU isn’t present, we’ll auto-disable.
# USE_USB ?= 1

# Common TinyUSB locations; add more if your tree differs
TINYUSB_CANDIDATES := \
  neuralSPOT/extern/tinyusb/src \
  neuralspot/extern/tinyusb/src \
  neuralSPOT/extern/AmbiqSuite/R5.3.0/third_party/TinyUSB/tinyusb/src \
  neuralSPOT/extern/AmbiqSuite/R5.3.0/third_party/tinyusb/src \
  neuralSPOT/extern/AmbiqSuite/R5.3.0/third_party/usb/tinyusb/src

# Pick the first candidate that actually holds tusb.h
TINYUSB_SRC := $(firstword $(foreach d,$(TINYUSB_CANDIDATES),$(if $(wildcard $(d)/tusb.h),$(d),)))

# ifeq ($(USE_USB),1)
#   ifneq ($(TINYUSB_SRC),)
#     $(info TinyUSB found at $(TINYUSB_SRC))
#     modules      += neuralspot/neuralspot/ns-usb
#     DEFINES      += NS_USB_PRESENT CFG_TUSB_MCU=OPT_MCU_APOLLO5
#     includes_api += $(TINYUSB_SRC)
#   else
#     $(warning TinyUSB not found; building WITHOUT USB. Set USE_USB=0 to silence this or install TinyUSB and re-run.)
#     USE_USB := 0
#   endif
# endif

# ========== Test discovery & selection ==========
TEST_DIRS := $(sort $(shell find GeneratedTests -type f -name test_runner.c -exec dirname {} \; 2>/dev/null))
ifeq ($(TEST_DIRS),)
$(error No test_runner.c found under GeneratedTests/. Generate runners first, then re-run make.)
endif

TEST_DIR ?= $(firstword $(TEST_DIRS))
TEST_NAME := $(notdir $(TEST_DIR))

# ========== App name & binary targets ==========
local_app_name := $(TEST_NAME)
TARGET         := $(local_app_name)

targets  := $(BINDIR)/$(local_app_name).axf
targets  += $(BINDIR)/$(local_app_name).bin

# ========== Sources & include paths ==========
sources      :=
sources      += $(wildcard src/*.c) $(wildcard src/*.cc) $(wildcard src/*.cpp) $(wildcard src/*.s)
sources      += $(TEST_DIR)/test_runner.c
# Add Unity source files
sources      += downloads/unity/src/unity.c
# Add model source files
sources      += $(wildcard $(TEST_DIR)/src/*.c) $(wildcard $(TEST_DIR)/src/*.cpp)
# Add AmbiqSuite system initialization
sources      += neuralSPOT/extern/AmbiqSuite/R5.3.0/src/apollo510/system_apollo510.c

# Allow includes for src/, the test dir, and its includes-api subdir
includes_api := src $(includes_api)
includes_api += $(TEST_DIR) $(TEST_DIR)/includes-api
# Add Unity testing framework
includes_api += downloads/unity/src
# Add ns-harness includes
includes_api += neuralspot/neuralspot/ns-harness/includes-api
# Add ns-core includes
includes_api += neuralspot/neuralspot/ns-core/includes-api
# Add ns-utils includes
includes_api += neuralspot/neuralspot/ns-utils/includes-api
# Add ns-cmsis-nn includes
includes_api += ns-cmsis-nn/Include
# Add ns-peripherals includes
includes_api += neuralspot/neuralspot/ns-peripherals/includes-api
# Add ns-rpc includes
includes_api += neuralspot/neuralspot/ns-rpc/includes-api
# Add ns-ipc includes
includes_api += neuralspot/neuralspot/ns-ipc/includes-api
# Add ns-audio includes
includes_api += neuralspot/neuralspot/ns-audio/includes-api
# Add ns-uart includes
includes_api += neuralspot/neuralspot/ns-uart/includes-api
# Add ns-features includes
includes_api += neuralspot/neuralspot/ns-features/includes-api
# Add ns-i2c includes
includes_api += neuralspot/neuralspot/ns-i2c/includes-api
# Add ns-spi includes
includes_api += neuralspot/neuralspot/ns-spi/includes-api
# Add erpc includes
includes_api += neuralspot/extern/erpc/R1.9.1/includes-api
# Add ns-usb includes
# includes_api += neuralspot/neuralspot/ns-usb/includes-api  # Disabled - requires TinyUSB
# Disable USB support in erpc
DEFINES += USB_PRESENT=0
# Override erpc module to exclude USB files
override modules := $(filter-out neuralspot/extern/erpc/R1.9.1, $(modules))
modules += neuralspot/extern/erpc/R1.9.1
# AmbiqSuite R5.3.0 includes (comprehensive)
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/boards/apollo510_evb/bsp
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/CMSIS/ARM/Include
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/mcu/apollo510
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/mcu/apollo510/hal
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/mcu/apollo510/hal/mcu
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/CMSIS/AmbiqMicro/Include
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/devices
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/utils
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/third_party/FreeRTOSv10.5.1/Source/include
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/src
includes_api += neuralSPOT/extern/AmbiqSuite/R5.3.0/third_party/FreeRTOSv10.5.1/Source/portable/GCC/AMapollo5

# Prebuilt AmbiqSuite libraries
lib_prebuilt += neuralSPOT/extern/AmbiqSuite/R5.3.0/lib/apollo510/libam_hal.a
lib_prebuilt += neuralSPOT/extern/AmbiqSuite/R5.3.0/lib/apollo510/evb/libam_bsp.a

# ========== Linker selection (NeuralSPOT provides scripts) ==========
ifeq ($(BOARD),apollo5b)
  LINKER_EXT := _sbl
else ifeq ($(BOARD),apollo4p)
  LINKER_EXT :=
endif
LINKER_EXT := _sbl

ifeq ($(TOOLCHAIN),arm)
  LINKER_FILE := neuralspot/neuralspot/ns-core/src/$(BOARD)/$(COMPDIR)/linker_script$(LINKER_EXT).sct
else ifeq ($(TOOLCHAIN),arm-none-eabi)
  LINKER_FILE := neuralspot/neuralspot/ns-core/src/$(BOARD)/$(COMPDIR)/linker_script$(LINKER_EXT).ld
endif

# ========== Objects/Deps & flags ==========
objects      = $(call source-to-object,$(sources))
dependencies = $(subst .o,.d,$(objects))

CFLAGS     += $(addprefix -D,$(DEFINES))

# Sanitize include list: keep only real directories (filters out stray files/commas)
INCLUDE_DIRS := $(foreach d,$(includes_api),$(if $(wildcard $(d)/.),$(d),))
CFLAGS       += $(addprefix -I ,$(INCLUDE_DIRS))

# NOTE: Toolchain-specific flags are injected by neuralspot_toolchain.mk via CCFLAGS/CONLY_FLAGS/ASMFLAGS/LFLAGS.

# ========== Default goal ==========
.PHONY: all
all: $(BINDIR) $(libraries) $(override_libraries) $(objects) $(targets)

# Bring in module makefiles (defines libraries, include paths, etc.)
include $(addsuffix /module.mk,$(modules))

# ========== Clean ==========
.PHONY: clean
clean:
ifeq ($(OS),Windows_NT)
	@echo "Windows_NT"
	@echo $(Q) $(RM) -rf $(BINDIR)/*
	$(Q) $(RM) -rf $(BINDIR)/*
else
	$(Q) $(RM) -rf $(BINDIR) $(JLINK_CF)
endif

# ========== Deps ==========
ifneq "$(MAKECMDGOALS)" "clean"
  -include $(dependencies)
endif

# ========== Build rules (absolute tool paths) ==========
$(BINDIR):
	$(Q) $(MKD) -p $@

$(BINDIR)/%.o: %.cc
	@echo " Compiling $(RUN_CC) $< to make $@"
	$(Q) $(MKD) -p $(@D)
	$(Q) $(RUN_CC) -c $(CFLAGS) $(CCFLAGS) $< -o $@

$(BINDIR)/%.o: %.cpp
	@echo " Compiling $(RUN_CC) $< to make $@"
	$(Q) $(MKD) -p $(@D)
	$(Q) $(RUN_CC) -c $(CFLAGS) $(CCFLAGS) $< -o $@

$(BINDIR)/%.o: %.c
	@echo " Compiling $(RUN_CC) $< to make $@"
	$(Q) $(MKD) -p $(@D)
	$(Q) $(RUN_CC) -c $(CFLAGS) $(CONLY_FLAGS) $< -o $@

$(BINDIR)/%.o: %.s
	@echo " Assembling $(RUN_CC) $<"
	$(Q) $(MKD) -p $(@D)
	$(Q) $(RUN_CC) -c $(ASMFLAGS) $< -o $@

$(BINDIR)/$(local_app_name).axf: $(objects) $(libraries) $(lib_prebuilt) $(override_libraries)
	@echo " Linking $(RUN_CC) -> $@"
	$(Q) $(MKD) -p $(@D)
ifeq ($(TOOLCHAIN),arm)
	$(Q) $(RUN_LD) $^ $(LFLAGS) --list=$*.map -o $@
else
	$(Q) $(RUN_CC) -Wl,-T,$(LINKER_FILE) -o $@ $^ $(LFLAGS)
endif

ifeq ($(TOOLCHAIN),arm)
$(BINDIR)/$(local_app_name).bin: $(BINDIR)/$(local_app_name).axf
	@echo " Copying to $@..."
	$(Q) $(MKD) -p $(@D)
	$(Q) $(RUN_OBJCOPY) $(CPFLAGS) $@ $<
	$(Q) $(RUN_OBJDUMP) $(ODFLAGS) $< --output $*.txt
else
$(BINDIR)/$(local_app_name).bin: $(BINDIR)/$(local_app_name).axf
	@echo " Copying to $@..."
	$(Q) $(MKD) -p $(@D)
	$(Q) $(RUN_OBJCOPY) $(CPFLAGS) $< $@
	$(Q) $(RUN_OBJDUMP) $(ODFLAGS) $< > $(@:.bin=.lst)
endif

# ========== J-Link deploy/view ==========
$(JLINK_CF):
	@echo " Creating JLink command sequence input file..."
	$(Q) mkdir -p $(dir $@)
	$(Q) echo "ExitOnError 1" > $@
	$(Q) echo "Reset" >> $@
	$(Q) echo "LoadFile $(BINDIR)/$(TARGET).bin, $(JLINK_PF_ADDR)" >> $@
	$(Q) echo "Exit" >> $@

.PHONY: deploy
deploy: $(JLINK_CF) $(BINDIR)/$(local_app_name).bin
	@echo " Deploying to device (ensure JLink USB connected and powered on)..."
	@if command -v $(JLINK) >/dev/null 2>&1; then \
		$(JLINK) $(JLINK_CMD); \
	else \
		echo "J-Link not found. Install J-Link software or use alternative deployment method."; \
		echo "Binary available at: $(BINDIR)/$(local_app_name).bin"; \
		exit 1; \
	fi

.PHONY: view
view:
	@echo " Viewing SWO output (ensure JLink USB connected and powered on)..."
	@if command -v $(JLINK_SWO) >/dev/null 2>&1; then \
		$(JLINK_SWO) $(JLINK_SWO_CMD); \
	else \
		echo "J-Link SWO Viewer not found. Install J-Link software or use alternative debugging method."; \
		exit 1; \
	fi

# Convenience: show binary location
.PHONY: show-binary
show-binary: $(BINDIR)/$(local_app_name).bin
	@echo "Binary available at: $(BINDIR)/$(local_app_name).bin"
	@echo "Size: $$(du -h $(BINDIR)/$(local_app_name).bin | cut -f1)"

# Convenience: list discovered tests and the selected TEST_DIR
.PHONY: list-tests
list-tests:
	@echo "Discovered tests:"
	@$(foreach d,$(TEST_DIRS),echo "  $(d)";)
	@echo ""
	@echo "Selected TEST_DIR=$(TEST_DIR)"

# ========== Doctor ==========
.PHONY: doctor
doctor:
	@echo "ARM_GCC_PATH=$(ARM_GCC_PATH)"
	@echo "RUN_CC=$(RUN_CC)"
	@echo "PATH=$$PATH"
	@echo "command -v arm-none-eabi-gcc:"; command -v arm-none-eabi-gcc || true
	@echo "ls -l $(ARM_GCC_PATH)/arm-none-eabi-gcc:"; ls -l "$(ARM_GCC_PATH)/arm-none-eabi-gcc" || true
	@echo "file arm-none-eabi-gcc:"; (command -v file >/dev/null && file "$(ARM_GCC_PATH)/arm-none-eabi-gcc") || echo "no 'file' utility"
	@echo "readelf interpreter:"; (command -v readelf >/dev/null && readelf -Wl "$(ARM_GCC_PATH)/arm-none-eabi-gcc" | sed -n 's/.*interpreter: \(.*\)]/\1/p') || echo "no 'readelf'"
	@echo "trying to run '$(RUN_CC) --version' ..."
	@-"$(RUN_CC)" --version || echo "FAILED to execute compiler"
